INSERT INTO combinedVehicleStopsSearchDetails ( stop_id, search_details_id, search_details_type, search_details_description )
SELECT Vehicle_stops_search_details_2015_datasd.stop_id, Vehicle_stops_search_details_2015_datasd.search_details_id, Vehicle_stops_search_details_2015_datasd.search_details_type, Vehicle_stops_search_details_2015_datasd.search_details_description
FROM Vehicle_stops_search_details_2015_datasd;
